"use client";

import { Button } from "@/components/ui/button";
import { Download, MessageCircle } from "lucide-react";

interface ShareButtonsProps {
  products: {
    name: string;
    currentStock: number;
    minStock: number;
    unit: string;
    reorderQty: number;
    supplierName?: string | null;
  }[];
}

function getDate() {
  return new Date().toLocaleDateString("en-PK", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function ShareButtons({ products }: ShareButtonsProps) {
  async function handleDownload() {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    const date = getDate();
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 18;
    // A4 usable width = 210 - 18*2 = 174mm; columns sum to 174
    const colWidths = [8, 52, 32, 30, 26, 26];
    const headers = ["#", "Product", "Stock / Min", "Shortage", "Reorder", "Supplier"];
    const rowH = 8;
    let y = margin;

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Restock List - Al-Madina General Store", margin, y);
    y += 7;

    // Sub-title
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Date: ${date}   |   ${products.length} item${products.length !== 1 ? "s" : ""} need restocking`, margin, y);
    y += 8;
    doc.setTextColor(0);

    // Table header
    doc.setFillColor(26, 26, 26);
    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.rect(margin, y, pageW - margin * 2, rowH, "F");
    let x = margin;
    headers.forEach((h, i) => {
      doc.text(h, x + 2, y + 5.5);
      x += colWidths[i];
    });
    y += rowH;

    // Rows
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    products.forEach((p, idx) => {
      const short = p.minStock - p.currentStock;
      const shortage = short > 0 ? `${short} ${p.unit}s short` : "At threshold";
      const cells = [
        `${idx + 1}`,
        p.name,
        `${p.currentStock} / ${p.minStock} ${p.unit}s`,
        shortage,
        `${p.reorderQty} ${p.unit}s`,
        p.supplierName ?? "—",
      ];

      // Alternating row background
      if (idx % 2 === 1) {
        doc.setFillColor(249, 250, 251);
        doc.rect(margin, y, pageW - margin * 2, rowH, "F");
      }

      doc.setTextColor(0);
      x = margin;
      cells.forEach((cell, i) => {
        const maxW = colWidths[i] - 4;
        const text = doc.splitTextToSize(cell, maxW)[0] ?? cell;
        doc.text(text, x + 2, y + 5.5);
        x += colWidths[i];
      });

      // Row border
      doc.setDrawColor(229, 231, 235);
      doc.line(margin, y + rowH, margin + (pageW - margin * 2), y + rowH);
      y += rowH;
    });

    // Footer
    y += 8;
    doc.setFontSize(8.5);
    doc.setTextColor(150);
    doc.text(`Generated by Maal Manager  •  Gulberg, Lahore`, margin, y);

    doc.save("restock-list.pdf");
  }

  function handleWhatsApp() {
    const date = getDate();
    const lines = products.map((p, i) => {
      const short = p.minStock - p.currentStock;
      const shortage = short > 0 ? `${short} ${p.unit}s short` : "At threshold";
      const supplier = p.supplierName ? `\n   Supplier: ${p.supplierName}` : "";
      return `${i + 1}. *${p.name}*\n   Stock: ${p.currentStock}/${p.minStock} ${p.unit}s\n   Shortage: ${shortage}\n   Reorder: ${p.reorderQty} ${p.unit}s${supplier}`;
    });

    const message =
      `*Restock List - Al-Madina General Store*\n` +
      `${date}\n` +
      `${products.length} item${products.length !== 1 ? "s" : ""} need restocking\n\n` +
      `─────────────────────\n\n` +
      lines.join("\n\n") +
      `\n\n─────────────────────\n` +
      `_Generated by Maal Manager • Gulberg, Lahore_`;

    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, "_blank");
  }

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="lg" className="gap-2" onClick={handleDownload}>
        <Download className="h-4 w-4" />
        Download PDF
      </Button>
      <Button
        variant="outline"
        size="lg"
        className="gap-2 text-emerald-700 border-emerald-300 hover:bg-emerald-50 dark:text-emerald-400 dark:border-emerald-800 dark:hover:bg-emerald-950/40"
        onClick={handleWhatsApp}
      >
        <MessageCircle className="h-4 w-4" />
        Share on WhatsApp
      </Button>
    </div>
  );
}
